[package]
name = "bipartite"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
fixedbitset = { workspace = true }
csr = { workspace = true }
