[package]
name = "lcp"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
suffix_array = { workspace = true }
rmq = { workspace = true }
