[package]
name = "rmq"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ops = { path = "../../math/ops" }
sparse_table = { path = "../sparse_table" }
rustc-hash = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
