[package]
name = "rmq"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ops = { workspace = true }
sparse_table = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
