[package]
name = "tree_dp"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
csr = { path = "../csr" }
ops = { path = "../../math/ops" }
thiserror = { workspace = true }
fixedbitset = { workspace = true }
