[package]
name = "tree_dp"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
csr = { workspace = true }
ops = { workspace = true }
thiserror = { workspace = true }
fixedbitset = { workspace = true }
